
name: Create specific-size Docs
on:
  workflow_dispatch:
    inputs:
      paper_layout:
        description: 'Select PDF Output Dimensions'
        required: true
        default: 'letter'
        type: choice
        options:
          - 'letter'
          - 'letter-landscape'
          - 'tabloid'
          - 'tabloid-landscape'
        
        

jobs:
  build-docs:
    name: Build documentation (PDF)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1


      - name: Install Rust & Auto-Cache
        uses: actions-rust-lang/setup-rust-toolchain@v2

      - name: Compile documentation
        run: |
          if [ "${{ github.event.inputs.paper_layout }}" = "letter-landscape" ]; then
            prefill_args=(--input-field paper="us-letter" --input-field flipped="true")
          fi
          if [ "${{ github.event.inputs.paper_layout }}" = "letter" ]; then
            prefill_args=(--input-field paper="us-letter" --input-field flipped="false")
          fi
          if [ "${{ github.event.inputs.paper_layout }}" = "tabloid-landscape" ]; then
            prefill_args=(--input-field paper="us-tabloid" --input-field flipped="true")
          fi
          if [ "${{ github.event.inputs.paper_layout }}" = "tabloid" ]; then
            prefill_args=(--input-field paper="us-tabloid" --input-field flipped="false")
          fi
          echo cargo run --profile dev-fast --package=typst-docs -- compile --format pdf --release "${prefill_args[@]}"
          cargo run --profile dev-fast --package=typst-docs -- compile --format pdf --release "${prefill_args[@]}"
          

      - name: Rename documentation file
        run: mv docs/dist/docs.pdf typst-documentation.pdf
        
      - name: Generate Datestamp
        id: date
        shell: bash
        run: |
          # Generates a stamp like YYYYMMDD
          echo "stamp=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
  
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          # Formats output as: resvg-windows-20260909-b42
          name: typst-${{ github.event.inputs.paper_layout }}-${{ steps.date.outputs.stamp }}-b${{ github.run_number }}
          path: typst-documentation.pdf
          if-no-files-found: error
          retention-days: 14
          
